site_name: MDS-2020-2-G6
site_description: Reposit√≥rio da disciplina de MDS
repo_url: https://github.com/fga-eps-mds/MDS-2020-2-G6 

theme:
    name: material

plugins:
    - search

nav:
    - Home: "index.md"
    - Sprints:
         - Sprint 0:
            - Planning (04/02): "sprints/sprint_0/Plannig_sprint_0.md"
            - Review: "sprints/sprint_0/Review_sprint_0.md"

