site_name: Hortum
site_description: Repositório do Projeto Hortum
repo_url: https://github.com/fga-eps-mds/2020.2-Hortum 
dev_addr: '127.0.0.1:8080'
edit_uri: ""

theme:
    name: material
    logo: img/logo.png
    favicon: img/logo.png
    palette:
        accent: green
    features:
        - navigation.tabs
        
extra_css:
  - stylesheets/extra.css

plugins:
    - search

nav:
    - Home: "index.md"
    - Projeto:
        - Documento de Visão: "Documento_de_visao.md"
        - Documento de Metodologia: "Documento_metodologia.md"
        - Documento de Arquitetura: "Documento_de_arquitetura.md"
    - Produto:
        - Protótipo: "Prototipo.md"
        - Guia de Estilo e Manual de Identidade Visual: "Guia_de_estilo_e_identidade_visual.md"
        - Product Backlog: "Product_Backlog.md"
        - Canvas: "Canvas.md"
    - Sprints:
        - Sprint 0:
            - Planning: "sprints/sprint_0/Planning_sprint_0.md"
            - Review: "sprints/sprint_0/Review_sprint_0.md"
        - Sprint 1:
            - Planning: "sprints/sprint_1/Planning_sprint_1.md"
            - Review: "sprints/sprint_1/Review_sprint_1.md"
        - Sprint 2:
            - Planning: "sprints/sprint_2/Planning_sprint_2.md"
            - Review: "sprints/sprint_2/Review_sprint_2.md"
        - Sprint 3:
            - Planning: "sprints/sprint_3/Planning_sprint_3.md"
            - Review: "sprints/sprint_3/Review_sprint_3.md"
        - Sprint 4:
            - Planning: "sprints/sprint_4/Planning_sprint_4.md"
            - Review: "sprints/sprint_4/Review_sprint_4.md"
        - Sprint 5:
            - Planning: "sprints/sprint_5/Planning_sprint_5.md"
            - Review: "sprints/sprint_5/Review_sprint_5.md"
        - Sprint 6:
            - Planning: "sprints/sprint_6/Planning_sprint_6.md"
            - Review: "sprints/sprint_6/Review_sprint_6.md"
        - Sprint 7:
            - Planning: "sprints/sprint_7/Planning_sprint_7.md"
            - Review: "sprints/sprint_7/Review_sprint_7.md"
        - Sprint 8:
            - Planning: "sprints/sprint_8/Planning_sprint_8.md"
    - Contribuição:
        - Como contribuir: "CONTRIBUTING.md"
        - Política de Contribuição: "Politica_de_Contribuicao.md"
        - Código de Conduta: "CODE_OF_CONDUCT.md"
